basePath: /
definitions:
  controllers.ChangePasswordResponse:
    properties:
      message:
        type: string
    type: object
  controllers.ErrorResp:
    properties:
      error:
        type: string
    type: object
  controllers.FoodInput:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
      restaurant_id:
        type: integer
    required:
    - name
    - price
    - restaurant_id
    type: object
  controllers.FoodResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      restaurant_id:
        type: integer
    type: object
  controllers.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  controllers.LoginResponse:
    properties:
      token:
        type: string
    type: object
  controllers.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
      profile:
        properties:
          bio:
            type: string
          full_name:
            type: string
        required:
        - full_name
        type: object
    required:
    - email
    - password
    type: object
  controllers.RegisterResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a sample server for a culinary review app.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Final Project Golang API
  version: "1.0"
paths:
  /auth/change-password:
    post:
      consumes:
      - application/json
      description: Change the password of the authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ChangePasswordResponse'
      summary: Change user password
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user and get JWT token.
      parameters:
      - description: Login Input
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LoginResponse'
      summary: Login a user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email, password and profile information.
      parameters:
      - description: Register Input
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RegisterResponse'
      summary: Register a new user
      tags:
      - auth
  /foods:
    get:
      description: Retrieve all food items in the restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.FoodResponse'
            type: array
      summary: Get all food items
      tags:
      - food
    post:
      consumes:
      - application/json
      description: Create a new food item in the restaurant
      parameters:
      - description: Food Input
        in: body
        name: food
        required: true
        schema:
          $ref: '#/definitions/controllers.FoodInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.FoodResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResp'
      summary: Create a new food item
      tags:
      - food
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
